/*
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.ide

import com.google.inject.Guice
import edu.eci.prot.dsl2.Dsl2RuntimeModule
import edu.eci.prot.dsl2.Dsl2StandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class Dsl2IdeSetup extends Dsl2StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new Dsl2RuntimeModule, new Dsl2IdeModule))
	}
	
}
