/*
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Dsl2RuntimeModule extends AbstractDsl2RuntimeModule {
}
