/*
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Dsl2StandaloneSetup extends Dsl2StandaloneSetupGenerated {

	def static void doSetup() {
		new Dsl2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
