/**
 * generated by Xtext 2.12.0
 */
package edu.eci.prot.dsl2.dsl2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.eci.prot.dsl2.dsl2.Feature#getName <em>Name</em>}</li>
 *   <li>{@link edu.eci.prot.dsl2.dsl2.Feature#isMany <em>Many</em>}</li>
 *   <li>{@link edu.eci.prot.dsl2.dsl2.Feature#isDiagnostic <em>Diagnostic</em>}</li>
 *   <li>{@link edu.eci.prot.dsl2.dsl2.Feature#isTransient <em>Transient</em>}</li>
 *   <li>{@link edu.eci.prot.dsl2.dsl2.Feature#getType <em>Type</em>}</li>
 *   <li>{@link edu.eci.prot.dsl2.dsl2.Feature#getItems <em>Items</em>}</li>
 * </ul>
 *
 * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getFeature_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.eci.prot.dsl2.dsl2.Feature#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Many</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Many</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Many</em>' attribute.
   * @see #setMany(boolean)
   * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getFeature_Many()
   * @model
   * @generated
   */
  boolean isMany();

  /**
   * Sets the value of the '{@link edu.eci.prot.dsl2.dsl2.Feature#isMany <em>Many</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Many</em>' attribute.
   * @see #isMany()
   * @generated
   */
  void setMany(boolean value);

  /**
   * Returns the value of the '<em><b>Diagnostic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Diagnostic</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Diagnostic</em>' attribute.
   * @see #setDiagnostic(boolean)
   * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getFeature_Diagnostic()
   * @model
   * @generated
   */
  boolean isDiagnostic();

  /**
   * Sets the value of the '{@link edu.eci.prot.dsl2.dsl2.Feature#isDiagnostic <em>Diagnostic</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Diagnostic</em>' attribute.
   * @see #isDiagnostic()
   * @generated
   */
  void setDiagnostic(boolean value);

  /**
   * Returns the value of the '<em><b>Transient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Transient</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transient</em>' attribute.
   * @see #setTransient(boolean)
   * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getFeature_Transient()
   * @model
   * @generated
   */
  boolean isTransient();

  /**
   * Sets the value of the '{@link edu.eci.prot.dsl2.dsl2.Feature#isTransient <em>Transient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transient</em>' attribute.
   * @see #isTransient()
   * @generated
   */
  void setTransient(boolean value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Type)
   * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getFeature_Type()
   * @model
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link edu.eci.prot.dsl2.dsl2.Feature#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Items</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Items</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' attribute list.
   * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getFeature_Items()
   * @model unique="false"
   * @generated
   */
  EList<String> getItems();

} // Feature
