/**
 * generated by Xtext 2.12.0
 */
package edu.eci.prot.dsl2.dsl2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getType()
 * @model
 * @generated
 */
public interface Type extends AbstractElement
{
} // Type
