/*
 * generated by Xtext 2.12.0
 */
package edu.eci.prot.dsl2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDsl2ScopeProvider extends DelegatingScopeProvider {
}
