/**
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.ui.contentassist;

import edu.eci.prot.dsl2.ui.contentassist.AbstractDsl2ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class Dsl2ProposalProvider extends AbstractDsl2ProposalProvider {
}
