/**
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.eci.prot.dsl2.Dsl2RuntimeModule;
import edu.eci.prot.dsl2.Dsl2StandaloneSetup;
import edu.eci.prot.dsl2.ide.Dsl2IdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class Dsl2IdeSetup extends Dsl2StandaloneSetup {
  @Override
  public Injector createInjector() {
    Dsl2RuntimeModule _dsl2RuntimeModule = new Dsl2RuntimeModule();
    Dsl2IdeModule _dsl2IdeModule = new Dsl2IdeModule();
    return Guice.createInjector(Modules2.mixin(_dsl2RuntimeModule, _dsl2IdeModule));
  }
}
