/**
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.ide;

import edu.eci.prot.dsl2.ide.AbstractDsl2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Dsl2IdeModule extends AbstractDsl2IdeModule {
}
