/**
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.ui;

import edu.eci.prot.dsl2.ui.AbstractDsl2UiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Dsl2UiModule extends AbstractDsl2UiModule {
  public Dsl2UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
