/**
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.dsl2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
