/**
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.dsl2;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.eci.prot.dsl2.dsl2.Entity#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link edu.eci.prot.dsl2.dsl2.Entity#isService <em>Service</em>}</li>
 *   <li>{@link edu.eci.prot.dsl2.dsl2.Entity#getImports <em>Imports</em>}</li>
 *   <li>{@link edu.eci.prot.dsl2.dsl2.Entity#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getEntity()
 * @model
 * @generated
 */
public interface Entity extends Type
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Super Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(Entity)
   * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getEntity_SuperType()
   * @model
   * @generated
   */
  Entity getSuperType();

  /**
   * Sets the value of the '{@link edu.eci.prot.dsl2.dsl2.Entity#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(Entity value);

  /**
   * Returns the value of the '<em><b>Service</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service</em>' attribute.
   * @see #setService(boolean)
   * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getEntity_Service()
   * @model
   * @generated
   */
  boolean isService();

  /**
   * Sets the value of the '{@link edu.eci.prot.dsl2.dsl2.Entity#isService <em>Service</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service</em>' attribute.
   * @see #isService()
   * @generated
   */
  void setService(boolean value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link edu.eci.prot.dsl2.dsl2.Import}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getEntity_Imports()
   * @model containment="true"
   * @generated
   */
  EList<Import> getImports();

  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference list.
   * The list contents are of type {@link edu.eci.prot.dsl2.dsl2.Feature}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Features</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference list.
   * @see edu.eci.prot.dsl2.dsl2.Dsl2Package#getEntity_Features()
   * @model containment="true"
   * @generated
   */
  EList<Feature> getFeatures();

} // Entity
