/**
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.scoping;

import edu.eci.prot.dsl2.scoping.AbstractDsl2ScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class Dsl2ScopeProvider extends AbstractDsl2ScopeProvider {
}
