/*
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Dsl2UiModule extends AbstractDsl2UiModule {
}
