/*
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.ui;

import com.google.inject.Injector;
import edu.eci.prot.dsl2.ui.internal.Dsl2Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Dsl2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Dsl2Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Dsl2Activator.getInstance().getInjector(Dsl2Activator.EDU_ECI_PROT_DSL2_DSL2);
	}
	
}
