/*
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.ui.tests;

import com.google.inject.Injector;
import edu.eci.prot.dsl2.ui.internal.Dsl2Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Dsl2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Dsl2Activator.getInstance().getInjector("edu.eci.prot.dsl2.Dsl2");
	}

}
