/**
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2;

import edu.eci.prot.dsl2.AbstractDsl2RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Dsl2RuntimeModule extends AbstractDsl2RuntimeModule {
}
