/**
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2;

import edu.eci.prot.dsl2.Dsl2StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Dsl2StandaloneSetup extends Dsl2StandaloneSetupGenerated {
  public static void doSetup() {
    new Dsl2StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
