/*
 * generated by Xtext 2.11.0
 */
package edu.eci.prot.dsl2.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Dsl2AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/eci/prot/dsl2/parser/antlr/internal/InternalDsl2.tokens");
	}
}
